// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfdisqcnrjynqcksnruo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZGlzcWNucmp5bnFja3NucnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDczMDcsImV4cCI6MjA2NTk4MzMwN30.CSsiDGa6fZdGN-_Fs9trt38whofVigTg5aRq_byZyc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);